---

##### PACKAGES ###################

- name: configure APT to install apache and modules from buster-backports
  template:
    src: etc_apt_preferences.d_99-apache2-buster-backports.j2
    dest: /etc/apt/preferences.d/99-apache2-buster-backports
    mode: 0644
  register: apache_apt_pinning

# refresh APT cache after updating APT preferences
- name: update apt cache # noqa 503
  become: yes
  apt:
    update_cache: yes
  when: apache_apt_pinning.changed

- name: install apache/php packages
  apt:
    state: present
    package:
      - apache2
      - libapache2-mod-evasive
      - libapache2-mod-md
      - libapache2-mod-fcgid
      - php-apcu
      - php
      - php-fpm

- name: remove mod-php (replaced with php-fpm)
  apt:
    package: libapache2-mod-php
    state: absent
  notify: restart apache

##### APACHE MODULES/CONFIGURATON #####

- name: copy apache2/php configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: 'etc_apache2_conf-available_security.conf.j2', dest: '/etc/apache2/conf-available/security.conf' }
    - { src: 'etc_apache2_conf-available_logging.conf.j2', dest: '/etc/apache2/conf-available/logging.conf' }
    - { src: 'etc_apache2_conf-available_ssl-common.conf.j2', dest: '/etc/apache2/conf-available/ssl-common.conf' }
    - { src: 'etc_apache2_conf-available_mod-md.conf.j2', dest: '/etc/apache2/conf-available/mod-md.conf' }
    - { src: 'etc_apache2_ports.conf.j2', dest: '/etc/apache2/ports.conf' }
    - { src: 'etc_php_7.3_fpm_pool.d_www.conf.j2', dest: '/etc/php/7.3/fpm/pool.d/www.conf' }
  notify:
    - reload apache
    - restart php-fpm

- name: disable unnecessary apache modules
  command: a2dismod {{ item }}
  args:
    removes: /etc/apache2/mods-enabled/{{ item }}.load
  with_items:
    - 'cgi'
    - 'php7.3' # conflicts with mpm_event
    - 'mpm_prefork' # conflicts with mpm_event
  notify: restart apache

- name: enable apache modules
  command: a2enmod {{ item }}
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"
  with_items:
    - 'auth_basic'
    - 'headers'
    - 'rewrite'
    - 'md'
    - 'ssl'
    - 'mpm_event'
    - 'proxy'
    - 'proxy_fcgi'
    - 'http2'
  notify: restart apache

- name: enable apache configuration snippets
  command: a2enconf {{ item }}
  args:
    creates: "/etc/apache2/conf-enabled/{{ item }}.conf"
  with_items:
    - 'security'
    - 'logging'
    - 'ssl-common'
    - 'mod-md'
    - 'php7.3-fpm'
  notify: reload apache

- include: apache-mod-evasive.yml

- name: copy apache sites config
  template:
    src: etc_apache2_sites-available_000-sites.conf.j2
    dest: /etc/apache2/sites-available/000-sites.conf
    mode: 0644
  notify: reload apache

- name: enable apache sites configuration
  command: a2ensite 000-sites
  args:
    creates: /etc/apache2/sites-enabled/000-sites.conf
  notify: reload apache

- name: remove apache/php configuration from previous versions of the role + default sites
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apache2/sites-enabled/sites.conf
    - /etc/apache2/sites-enabled/000-default.conf
    - /etc/apache2/sites-enabled/default-ssl.conf
    - /etc/apache2/sites-available/sites.conf
    - /var/www/html/index.html
    - /etc/php/7.3/apache2/conf.d/30-hide-header.ini
  notify: reload apache

##### FAIL2BAN #####

- name: copy apache fail2ban jail config
  template:
    src: etc_fail2ban_jail.d_apache.conf.j2
    dest: /etc/fail2ban/jail.d/apache.conf
    mode: 0600
  tags: fail2ban
  notify: reload fail2ban

##### SERVICE #####

- name: ensure apache/fail2ban configuration is applied (flush handlers)
  meta: flush_handlers

- name: enable apache service
  service: name=apache2 state=started enabled=yes
  when: apache_enable_service|bool
  tags: services

- name: disable apache service
  service: name=apache2 state=stopped enabled=no
  when: not apache_enable_service|bool
  tags: services

##### ANSIBLE USER #####

- name: add/remove the ansible user to/from the www-data group
  