---

galaxy_info:
  role_name: nginx
  author: "nodiscc <nodiscc@gmail.com>"
  description: "nginx web server"
  license: "GPL-3.0"
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - web
    - nginx
    - php
    - server
    - lemp

# the common role is recommended
dependencies: []
