##### RSYSLOG #####

- name: configure rsyslog
  template:
    src: etc_rsyslog.d_{{ item }}.conf.j2
    dest: /etc/rsyslog.d/{{ item }}.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
  with_items:
    - services-imfile # aggregate common/other role's services log files
    - discard # discard useless messages
    - singlefile # log all messages to /var/log/syslog

- name: remove rsyslog config files from old versions of the role
  file:
    state: absent
    path: /etc/rsyslog.d/{{ item }}.conf
  notify: restart rsyslog
  with_items:
    - fail2ban
    - apt
    - apache
    - php-fpm
    - netdata
    - gitea
    - samba
    - rsnapshot
    - mumble
    - nextcloud

# rsyslog is configured to send all messages to /var/log/syslog in singlefile.conf
# if a '*.*' filter is present in main rsyslog.conf, messages will be logged twice
- name: configure rsyslog to avoid duplicate messages
  lineinfile:
    path: /etc/rsyslog.conf
    state: absent
    regexp: '^\*\.\*'
  notify: restart rsyslog

##### SYSLOG FOWARDING OVER TCP+TLS #####

- name: install TLS protocol support for rsyslog 
  apt:
    package: "rsyslog-gnutls"
    state: present

- name: create rsyslog certs/keys directory
  file:
    state: directory
    path: /etc/ssl/syslog/

- name: upload syslog TLS certificate/key
  copy:
    src: "{{ playbook_dir }}/certificates/{{ ansible_hostname }}.{{ item }}"
    dest: "/etc/ssl/syslog/"
    mode: 0600
    owner: root
    group: root
  with_items:
    - "crt"
    - "pem"
  notify: restart rsyslog

- name: copy SSL/TLS configuration
  template: src=etc_rsyslog.d_ssl.conf dest=/etc/rsyslog.d/ssl.conf
  notify: restart rsyslog

#####

- name: run all notified handlers now
  meta: flush_handlers
