---

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  become: yes
  when: nginx_enable_service|bool

- name: reload nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes
  become: yes
  when: nginx_enable_service|bool
